# Generated by Django 6.1.1 on 2026-09-28 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ryba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=500)),
                ('wystepowanie', models.TextField(max_length=500)),
                ('styl_zycia', models.TextField(choices=[('rzeczna', 'rzeczna'), ('jeziorna', 'jeziorna'), ('morska', 'morska')])),
            ],
        ),
        migrations.CreateModel(
            name='OkresOchronny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_miesiaca', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('do_miesiaca', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('wymiar_ochronny', models.IntegerField()),
                ('ryba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rybyapp.ryba')),
            ],
        ),
    ]
